### ISSUE TITLE
wrong format of $d.tostring in runat

### ISSUE THREAD

**Issue by zhladik** [lukesampson/psutils#15]
in runat scriptlet:

\- $d.tostring("hh:mm")
+$d.tostring("HH:mm")

without this change every tasks scheduled before noon...
Quite bad bug because result echo is printed in correct format!

Maybe it does work in US locales PC {here in EU we have 24h locales time format), 
but then powershell is broken (very stupidly).

**Comment by lukesampson** [comment]
Thanks.
