### ISSUE TITLE
shasum cannot process file that have space in its name

### ISSUE THREAD

**Issue by talha131** [lukesampson/psutils#17]
shasum.cmd script splits file name at spaces. For example

```
$ shasum.cmd "SlackSetup 64.exe"
shasum: SlackSetup: no such file
shasum: 64.exe: no such file
```

I installed it via scoop.

```
$ scoop which shasum.cmd
Not a scoop shim.
C:\Users\talha\scoop\shims\shasum.cmd
```

**Comment by lukesampson** [comment]
Thanks for letting me know. I'll have a look at this tonight.

**Comment by lukesampson** [comment]
It turned out to be a problem with the way Scoop creates .cmd shims, so I've fixed it in Scoop.

You need to run `scoop update;scoop uninstall shasum;scoop install shasum` to recreate the shim.

**Comment by talha131** [comment]
Thanks a lot for prompt fix @lukesampson. I can confirm the issue is fixed.

**Comment by lukesampson** [comment]
Good to hear. You're welcome 👍
