### ISSUE TITLE
`sudo` does not work in PowerShell 6

### ISSUE THREAD

**Issue by leonyu** [lukesampson/psutils#20]
`sudo` does not work in PowerShell 6. 

Reproduce: 
* Install PowerShell 6 Core
* Run `sudo echo 1`
* Observe no UAC
* switch command to something that would otherwise require Admin privilege
* Observe command fails

**Comment by leonyu** [comment]
Found an odd workaround for now

`sudo sudo echo 1`

**Comment by jtc42** [comment]
Still not working in PS6, but I found a really janky workaround. Add a function in your profile:

```
function sudo
{
    $allArgs = $PsBoundParameters.Values + $args
    sudo.ps1 sudo.ps1 $allArgs
}
```

**Comment by TonyZZX** [comment]
> **Edit edit:** I've made a fork where I'm trying to port these to PS6. I eventually managed to get sudo working, https://github.com/jtc42/psutils/blob/master/sudo.ps1
> 
> Let me know if you have problems with it and I'll see what I can do.

Nice job! Could you submit a pull request?

**Comment by jtc42** [comment]
> > **Edit edit:** I've made a fork where I'm trying to port these to PS6. I eventually managed to get sudo working, https://github.com/jtc42/psutils/blob/master/sudo.ps1
> > Let me know if you have problems with it and I'll see what I can do.
> 
> Nice job! Could you submit a pull request?

Sorry for the slow reply. I was planning on submitting a PR, but my fork supports PS6 at the expense of PS5. I doubt this is something you want, so maybe creating a branch for PS6 is sensible, then I can PR into that?

**Comment by Jack-Works** [comment]
`sudo sudo` save my day, also have this problem in PowerShell 6

**Comment by zhoujin7** [comment]
Also have this problem in PowerShell 7.0.0-preview.3

**Comment by Stanzilla** [comment]
Just stumbled upon this, any chance of making this work @lukesampson?

**Comment by casz** [comment]
I submitted an updated PR #32 
Based on the reviews on #29

**Comment by jakoss** [comment]
Is the updated version released already? I have tried update'ing the sudo, but scoop claims that it's up to date:
![image](https://user-images.githubusercontent.com/3933348/140719309-ef971523-fe3f-417a-bdb0-549ee2eb377a.png)

Am i doing something wrong? I still have this issue in PowerShell 7.1.5. `sudo sudo` works as a workaround

**Comment by mpela81** [comment]
Having the same issue, with latest version of sudo / psutils (`sudo sudo` does not work either)

**Comment by devmcp** [comment]
Same issue here with latest sudo in PowerShell 7.2.1

```
~ $ sudo echo 1
sudo: you must be an administrator to run sudo
```

```
~ $ sudo sudo echo 1
sudo: you must be an administrator to run sudo
```
