### ISSUE TITLE
Access denied when using powershell command `Out-File` with `sudo`

### ISSUE THREAD

**Issue by yujinlin0224** [lukesampson/psutils#36]
```powershell
PS> cd C:\Program` Files
PS> sudo Write-Output "aaa" | Out-File a.txt
Out-File: Access to the path 'C:\Program Files\a.txt' is denied.
```
I also tried
`sudo 'Write-Output "aaa" | Out-File a.txt'` and
`sudo Write-Output "aaa" > a.txt` and
`sudo echo "aaa" > a.txt` but still not work.

**Comment by dnperfors** [comment]
This is likely by design, in linux you would typically do:
`Write-Output "aaa" | sudo Out-File a.txt`

However, this isn't working either and will result in an empty file...

**Comment by sean729** [comment]
Cannot believe this issue still exists in pwsh 7.1, and I haven't found an answer (yet). It seems a basic operation to perform.

**Comment by yujinlin0224** [comment]
Now [gsudo](https://github.com/gerardog/gsudo) is a better solution
