### ISSUE TITLE
Doesnt work with windows 11 24h2

### ISSUE THREAD

**Issue by nahid6970** [lukesampson/psutils#52]
sudo doesnt work with windows 11 24h2 because windows 11 24h2 has its own sudo tool in developer mode so when i try to use sudo it is referring to the windows sudo not the one here

here is the output i get when i use sudo with any command:

 sudo "any command"
output
Sudo is disabled on this machine. To enable it, go to the Developer Settings page in the Settings app

so when i enable the sudo on the developer option in windows setting it uses that sudo which is pretty bad and i dont like windows11 24h2 sudo which has very few functionality like u can only run any app as admin with that sudo. so no way to run any command with that sudo.

so is there any workaround to use ur sudo instead of windows default sudo?

**Comment by Licheng-Xu** [comment]
There is a sub-setting item under sudo setting item, select "inline", then the command output will display directly.

**Comment by yaoie-loop** [comment]
Use `sudo.ps1 [command]` instead of `sudo [command]` can make use.

**Comment by nahid6970** [comment]
> Use `sudo.ps1 [command]` instead of `sudo [command]` can make use.

it solved the problem but how about an idea change it to su so  we dont need the .ps1 currently i have added a script in my powershell profile so when i use su it will use sudo ? since the issue is gone for me i am closeing it

**Comment by evakili** [comment]
I declared an alias for sudo in my PS profile to overcome this issue:
```powershell
Set-Alias -Name sudo -Value sudo.ps1
```
