### ISSUE TITLE
ln forces absolute directories

### ISSUE THREAD

**Issue by nkm8** [lukesampson/psutils#9]
When I use ln, it creates the symbolic link using an absolute directory instead of relative.

Example:
```
cd C:\folder
mkdir test
ln -s test test2
dir /AL /S
```

Output:
```
04/24/2015  12:57 PM    <SYMLINKD>     test2 [C:\Folder\test]
```

**Comment by lukesampson** [comment]
Thanks, should be fixed now. If you installed with Scoop, it's just `scoop update ln` to get the new version.

**Comment by nkm8** [comment]
:+1: Thanks for the quick fix!

**Comment by lukesampson** [comment]
You're welcome—thanks for pointing it out.
